[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.12"
serde-wasm-bindgen = "0.5.0"
thiserror = "1.0.43"
wasm-bindgen = "0.2.87"
wee_alloc = "0.4.5"
